# Generated by Django 3.0.4 on 2020-03-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=100)),
                ('connection_string', models.CharField(max_length=150)),
                ('path', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=150)),
                ('connection_cert', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_access', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserConnections',
            fields=[
                ('user_connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Connection')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
    ]
